name: Deploy GitHub Pages without Jekyll Trash

on:
  push:
    branches: ["main"]

env:
  LANG: c.UTF-8
  LC_ALL: c.UTF-8
  
permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # === MAIN PAGE FROM README ===
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Проверяем изменения для сайта
      - name: Check for site changes
        id: site-check
        uses: dorny/paths-filter@v3
        with:
          filters: |
            site_changed:
              - '.github/**'
              - 'README.md'

      - name: Setup Pages
        if: steps.site-check.outputs.site_changed == 'true'
        uses: actions/configure-pages@v5

      - name: Install Pandoc
        if: steps.site-check.outputs.site_changed == 'true'
        run: sudo apt-get install -y pandoc

      - name: Build Clean HTML
        if: steps.site-check.outputs.site_changed == 'true'
        run: |

          # ------------------------------------------------
          # 1. Create ("index.html") from root README.md
          # ------------------------------------------------

          cat << 'EOF' > index.html
          <!DOCTYPE html><html lang="ru"><head>
              <meta charset="UTF-8">
              <meta name="description" content="Collection python scripts & utils" />
              <meta name="viewport" content="width=device-width, initial-scale=1">

              <title>python.utils</title>

              <meta property="og:title" content="Python Utils">
              <meta property="og:type" content="website">
              <meta property="og:url" content="https://vsky.space/python">
              <meta property="og:description" content="Collection python scripts & utils">
              <meta property="og:image" content="https://vsky.space/content/cover/python.jpg">
              <meta property="og:image:secure_url" content="https://vsky.space/content/cover/python.jpg">

              <meta name="twitter:card" content="summary_large_image">
              <meta name="twitter:title" content="Python Utils">
              <meta name="twitter:description" content="Collection python scripts & utils">
              <meta name="twitter:image" content="https://vsky.space/content/cover/python.jpg">
              <meta name="twitter:site" content="@AleksandrovskyV">

              <link rel="canonical" href="http://vsky.space">
              
              <!-- lock href for link and images -->
              <base href="/python/">

              <!-- script cleaner "/"" in end path bar -->
              <script>{let p=location.pathname; if(p.endsWith(".html"))p=p.slice(0,-5); if(p.endsWith("index"))p=p.slice(0,-5); if(p.endsWith("/"))p=p.slice(0,-1); if(p!==location.pathname){history.replaceState(null,"",p+location.search+location.hash);}}</script>
          EOF

          # paste styles.css
          echo '<style>' >> index.html
          cat ./.github/style.css >> index.html
          echo '</style>' >> index.html          

          # close <head> and create body content block
          echo '</head><body><div class="container-lg px-3 my-5 markdown-body">' >> index.html

          # 1. remove hubonly marks from README.md
          #sed -E 's|<span class="hubonly">.*?</span>||g' README.md | tr -d '\r' | pandoc -f markdown-yaml_metadata_block -t html > temp.html


          # 1. Убираем hubonly и динамически разворачиваем блок workflowlink прямо в Markdown
          sed -E 's|<span class="hubonly">.*?</span>||g' README.md | \
          sed "s|<div class=\"workflowlink\"><\/div>|<hr><p class=\"workflowlink\">html собран этим <a href=\"https://github.com/${GITHUB_REPOSITORY}/tree/main/.github\">workflow</a><\/p>|g" | \
          tr -d '\r' | pandoc -f markdown-yaml_metadata_block -t html > temp.html

          cat temp.html | tr '\n' ' ' | tr '\r' ' ' > temp_flat.html

          # 2. Search <p class="abblock">
          cat temp_flat.html | awk 'BEGIN{RS="<p class=\"abblock\">"} /class=\"exe\"/{print "<p class=\"abblock\">" $0}' | while read -r ab_block; do
            
            if [ -z "$ab_block" ] || [ "$ab_block" = "<p class=\"abblock\">" ]; then continue; fi
            
            # ger URL from href link in <ab_block>
            repo_url=$(echo "$ab_block" | grep -oP 'https://github.com/[^/]+/[^/ ">\r\n]+' | head -n 1)
            
            if [ ! -z "$repo_url" ]; then
              repo_path=$(echo "$repo_url" | sed 's|https://github.com/||' | cut -d'/' -f1,2)
              echo "Found repo: $repo_url (Путь для API: $repo_path)"
              
              # call API GitHub for get link
              DOWNLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${repo_path}/releases/latest" | jq -r '.assets[]? | select(.name | endswith(".exe")) | .browser_download_url' | head -n 1)

              echo "URL: $DOWNLOAD_URL"

              if [ ! -z "$DOWNLOAD_URL" ] && [ "$DOWNLOAD_URL" != "null" ] && [ "$DOWNLOAD_URL" != "" ]; then
                echo "Succes get link: $DOWNLOAD_URL"
                escaped_url=$(echo "$repo_url" | sed 's/[&/]/\\&/g')
                escaped_dl=$(echo "$DOWNLOAD_URL" | sed 's/[&/]/\\&/g')
                
                # replace empty div <exe> 
                sed -i -E "s|href=\"$escaped_url\"([^>]*>)([^<]*)</a>[^<]*/[^<]*<span class=\"exe\"><\/span>|href=\"$escaped_url\"\1\2</a> / <span class=\"exe\">.<a href=\"$escaped_dl\">exe</a><\/span>|g" temp_flat.html
              else
                echo "Error: Empty release"
              fi
            else
              echo "Error: not found url in readme"
            fi
          done

          cat temp_flat.html > temp.html
          rm temp_flat.html

          # Все замены летят напрямую в index.html без создания root_base.html
          cat temp.html | sed 's/\xF0\x9F\x94\xB9 /<span class="cdot"><\/span>/g' | \
          sed -E 's|<img([^>]+)src="([^"]*/)?([^/"]+)\.svg"([^>]*)>|<img\1src="\2\3.svg" class="svgico"\4><div class="line"><\/div>|g' | \
          sed -E 's|<h1 id="([^"]+)">([^<]+)</h1>|<h1 id="\1">user\/\2</h1>|g' >> index.html

          # remove temp
          rm temp.html
          
          echo '</div></body></html>' >> index.html
          
          # --------------- CREATE COPY W TARGET NAME -------------

          # Copy index.html but with target name 
          cp index.html python

          # Say GitHub Pages reback file on call
          echo -e "filtered_content:\n  - python" > _config.yml


      - name: Upload artifact
        if: steps.site-check.outputs.site_changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        if: steps.site-check.outputs.site_changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v4

